In [1]:
import kagglehub    
path = kagglehub.dataset_download("undefinenull/million-song-dataset-spotify-lastfm")

print("Path to dataset files:", path)


Path to dataset files: C:\Users\ljm47\.cache\kagglehub\datasets\undefinenull\million-song-dataset-spotify-lastfm\versions\1


In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data_path = Path("C:/Users/ljm47/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1")

song_data_path = data_path/ 'Music info.csv'
user_data_path = data_path/ 'User Listening History.csv'

In [4]:
#load songs data
df_songs = pd.read_csv(song_data_path, usecols=['track_id', 'name', 'artist', 'spotify_preview_url'])
df_songs.head(3)

track_id             name       artist  \
0  TRIOREW128F424EAF0   Mr. Brightside  The Killers   
1  TRRIVDJ128F429B0E8       Wonderwall        Oasis   
2  TROUVHL128F426C441  Come as You Are      Nirvana   

                                 spotify_preview_url  
0  https://p.scdn.co/mp3-preview/4d26180e6961fd46...  
1  https://p.scdn.co/mp3-preview/d012e536916c927b...  
2  https://p.scdn.co/mp3-preview/a1c11bb1cb231031...

In [ ]:
# !pip install dask[dataframe] 

In [5]:
import dask.dataframe as dd

df = dd.read_csv(user_data_path)
df.head()

# Using a Dask DataFrame instead of a Pandas DataFrame is a great choice when you're working with larger-than-memory datasets or want to parallelize computations for better performance.

#Lazy Execution: Dask builds a computation graph and doesn't execute operations immediately. You need .compute() to get results.

track_id                                   user_id  playcount
0  TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
1  TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
2  TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
3  TRTUCUY128F92E1D24  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
4  TRHDDQG12903CB53EE  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1

In [6]:
df  #values dont get printed as its stored in chunks, data is stored in meta data. to see value we need to use compute function

Dask DataFrame Structure:
              track_id user_id playcount
npartitions=9                           
                object  object     int64
                   ...     ...       ...
...                ...     ...       ...
                   ...     ...       ...
                   ...     ...       ...
Dask Name: read-csv, 1 graph layer

In [7]:
df.compute()

track_id                                   user_id  \
0        TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
1        TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
2        TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
3        TRTUCUY128F92E1D24  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
4        TRHDDQG12903CB53EE  b80344d063b5ccb3212f76538f3d9e43d87dca9e   
...                     ...                                       ...   
1079037  TRBKFKL128E078ED76  b7815dbb206eb2831ce0fe040d0aa537e2e800f7   
1079038  TRYFXPG128E078ECBD  b7815dbb206eb2831ce0fe040d0aa537e2e800f7   
1079039  TROBUUZ128F4263002  b7815dbb206eb2831ce0fe040d0aa537e2e800f7   
1079040  TROEWXC128F148C83E  b7815dbb206eb2831ce0fe040d0aa537e2e800f7   
1079041  TROHQNO128F146ECCB  b7815dbb206eb2831ce0fe040d0aa537e2e800f7   

         playcount  
0                1  
1                1  
2                1  
3                1  
4                1  
...            ...  
1079037          1  
1079038          1  
1079039          1  
1079040          1  
1079041          1  

[9711301 rows x 3 columns]

In [8]:
df.npartitions

9

In [9]:
#df.visualize(tasks = True)

In [10]:
# no of unique tracks in data
unique_tracks = df['track_id'].nunique() # this will give a PD series, untill we compute then only it will give a number 
unique_tracks = unique_tracks.compute()
unique_tracks


30459

In [11]:
# no of unqiue users
unqiue_users = df['user_id'].nunique()
unqiue_users = unqiue_users.compute()
unqiue_users


962037

In [12]:
unique_track_ids = df['track_id'].unique().compute()


In [13]:
unique_track_ids = unique_track_ids.tolist()
unique_track_ids

['TRIRLYL128F42539D1',
 'TRFUPBA128F934F7E1',
 'TRLQPQJ128F42AA94F',
 'TRTUCUY128F92E1D24',
 'TRHDDQG12903CB53EE',
 'TRGRDEC128F423C07D',
 'TRRYCBO128F932A2C7',
 'TRUTULC128F4293712',
 'TRAAHSY128F147BB5C',
 'TRDLMWP128F426BF6C',
 'TRMSZXT128F92F7816',
 'TRVODUZ128F934D094',
 'TRLXSNR128F429361D',
 'TRPUGUW128F426BF6F',
 'TRAUCNU128F42671EB',
 'TRVVWSW128F4292931',
 'TRADVZX128F426BF79',
 'TRDCZUX128F4263A74',
 'TRUYKTB128F1459197',
 'TRQLOHS128F42435AE',
 'TRCTFBL128F42934F3',
 'TRPGYLT128F428AD02',
 'TRAEGXU128F9304D31',
 'TRFNNFP128F146CB4B',
 'TRWCEKE128F93191BE',
 'TRADEOV128F9330E3B',
 'TRTQVKS128F92EF9BE',
 'TRSGIYX128F149F01F',
 'TRXWAZC128F9314B3E',
 'TRDOYFZ128F426E715',
 'TRBFXMJ12903CB50F6',
 'TRDSFKT12903CB510F',
 'TRRELZC128E078ED67',
 'TRURIYJ12903CB50FA',
 'TRISTWT128F1488FBB',
 'TRKPWGR128E078EE06',
 'TRJZLOA128F930369C',
 'TRUZPNY128F147FD23',
 'TRLSADE128F9321896',
 'TRONYHY128F92C9D11',
 'TRTDKMT128F92CDD87',
 'TRGAOLV128E0789D40',
 'TRCIVWB128F92FDBB3',
 'TRFWGOJ12

In [14]:
len(unique_track_ids)

30459

In [15]:
#filtered songs  --- creating a df showing only those songs that are unqiue in User info dataset
filtered_songs  = df_songs[df_songs['track_id'].isin(unique_track_ids)]
filtered_songs.reset_index(drop=True, inplace=True)

In [16]:
filtered_songs

track_id                name             artist  \
0      TRIOREW128F424EAF0      Mr. Brightside        The Killers   
1      TRRIVDJ128F429B0E8          Wonderwall              Oasis   
2      TRUEIND128F93038C4         Take Me Out    Franz Ferdinand   
3      TRXOGZT128F424AD74        Karma Police          Radiohead   
4      TRUJIIV12903CA8848              Clocks           Coldplay   
...                   ...                 ...                ...   
30454  TRXWSIN128F9339A11  Infinite Love Song  Maximilian Hecker   
30455  TRPIGDW12903CDEB2D     Slip of the Lip               Fact   
30456  TRQYCFV128F9322F50       Ryusei Rocket        アンティック-珈琲店-   
30457  TRHQCSH128F42724B7  Colors Of The Wind            ACIDMAN   
30458  TRGLMEM128F9322F63   Koi no Dependence        アンティック-珈琲店-   

                                     spotify_preview_url  
0      https://p.scdn.co/mp3-preview/4d26180e6961fd46...  
1      https://p.scdn.co/mp3-preview/d012e536916c927b...  
2      https://p.scdn.co/mp3-preview/399c401370438be4...  
3      https://p.scdn.co/mp3-preview/5a09f5390e2862af...  
4      https://p.scdn.co/mp3-preview/24c7fe858b234e3c...  
...                                                  ...  
30454  https://p.scdn.co/mp3-preview/8b3d529025fe3c60...  
30455  https://p.scdn.co/mp3-preview/cf64490291f9a600...  
30456  https://p.scdn.co/mp3-preview/d2668a5a3e0b1fda...  
30457  https://p.scdn.co/mp3-preview/8e22a7052ef3ecf7...  
30458  https://p.scdn.co/mp3-preview/5a61e031df174666...  

[30459 rows x 4 columns]

# creating Item-User interaction 
the matrix will contain 30k+ track ids in rows and 96k+ columns which represent user_ids and the value of each cell will be the playcount. 
since this will be a very large matrix, we will first reduce the size of the matrix by converting the track ids and users_id from String to integers to reduce the DF size
we will use the dask.dataframe.categorize() function which will help in this solution . 


In [17]:
import numpy as np
from scipy.sparse import csr_matrix

In [18]:
# Step 1  : Load the df
df = dd.read_csv(user_data_path)
# Step 2 : ensure playcount is numberic
df['playcount'] = df['playcount'].astype(np.float64)
df = df.categorize(columns=['user_id', 'track_id'])
#In Dask, df.categorize() is used to convert object or string columns to categorical types. This can significantly improve performance, 
# especially during operations like groupby(), join(), or merge().

# Step 3 : Convert user_id and track_id to numberic( categorical) values , basically each track_id and user_id is given a numberical(categorixal) value which is done by the categorize function on top
user_mapping = df['user_id'].cat.codes
track_mapping = df['track_id'].cat.codes



In [22]:
len(user_mapping)

9711301

In [23]:
df= df.assign(user_idx = user_mapping, 
              track_idx = track_mapping)

In [24]:
df
# two new columns are created showing the categorical value of each user and track id

Dask DataFrame Structure:
                      track_id          user_id playcount user_idx track_idx
npartitions=9                                                               
               category[known]  category[known]   float64    int32     int16
                           ...              ...       ...      ...       ...
...                        ...              ...       ...      ...       ...
                           ...              ...       ...      ...       ...
                           ...              ...       ...      ...       ...
Dask Name: assign, 12 graph layers

In [52]:
n_rows = df['user_idx'].count()
print(n_rows.compute())

9711301


In [53]:
# step 4 : compute the interaction matrix
interaction_array = df.groupby(['track_idx', 'user_idx'])['playcount'].sum().reset_index()
interaction_array

Dask DataFrame Structure:
              track_idx user_idx playcount
npartitions=1                             
                  int64    int64   float64
                    ...      ...       ...
Dask Name: reset_index, 16 graph layers

In [54]:
interaction_array = interaction_array.compute()
interaction_array

track_idx  user_idx  playcount
0                0     15780        3.0
1                0     76968        1.0
2                0    134525        2.0
3                0    231541        1.0
4                0    305348        1.0
...            ...       ...        ...
9711296      30458    902360        1.0
9711297      30458    913310        1.0
9711298      30458    922319        1.0
9711299      30458    925779        1.0
9711300      30458    943722        1.0

[9711301 rows x 3 columns]

In [55]:
# creating a sparse matrix 
row_indices = interaction_array['track_idx']
col_indices = interaction_array['user_idx']
values = interaction_array['playcount']

#building the matrix
n_tracks = unique_tracks
n_users = unqiue_users

sparse_matrix = csr_matrix((values, (row_indices, col_indices)), shape= (n_tracks, n_users))
print("Sparse matrix shape", sparse_matrix.shape)


Sparse matrix shape (30459, 962037)


In [ ]:
# import numpy as np
# from scipy.sparse import csr_matrix

# playcount = np.array([4, 5, 7, 9])
# songs= np.array([0, 1, 2, 1])
# user = np.array([0,1,2,1])
# sparse_matrix = csr_matrix((playcount, (songs, user)), shape=(3,4))

# print(sparse_matrix)
# print(sparse_matrix.shape)

  (0, 0)	4
  (1, 1)	14
  (2, 2)	7
(3, 4)


In [56]:
row_indices

0              0
1              0
2              0
3              0
4              0
           ...  
9711296    30458
9711297    30458
9711298    30458
9711299    30458
9711300    30458
Name: track_idx, Length: 9711301, dtype: int64

In [57]:
np.where(df['track_id'].cat.categories == "TROINZB128F932F740")

(array([17018], dtype=int64),)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity
ind = 17018  #taking an example
input_array = sparse_matrix[ind]
similarity_score = cosine_similarity( input_array , sparse_matrix)
similarity_score ## basically song A is in the row now and all songs a,b,c are columns.


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 7.20943546e-05]])

In [59]:
print(input_array.shape)
print(sparse_matrix.shape)


(1, 962037)
(30459, 962037)


In [60]:
np.sort(similarity_score[-6:][::-1]) 
similarity_score.shape # basically song A is in the row now and all songs a,b,c are columns.

(1, 30459)

In [61]:
np.argsort(similarity_score.ravel())[-6:][::-1]

array([17018, 24529, 28964,  3620,  9470,  7882], dtype=int64)

In [62]:
recommendations = df['track_id'].cat.categories[np.argsort(similarity_score.ravel())[-6:][::-1]]

In [63]:
recommendations # for the above input vector

Index(['TROINZB128F932F740', 'TRURCEI12903CA4395', 'TRYLWIW12903CA438D',
       'TRCVMAF12903D00E61', 'TRHRNEE12903CFDBD4', 'TRGEUXY128F4226B26'],
      dtype='object', name='track_id')

In [64]:
df_songs[df_songs['track_id'].isin(recommendations)]


track_id             name             artist  \
6013   TROINZB128F932F740    Crazy in Love            Beyoncé   
15899  TRCVMAF12903D00E61         Delirium          Satyricon   
29724  TRGEUXY128F4226B26  Monday Massacre           Mr. Oizo   
44767  TRYLWIW12903CA438D        Dreadlock  Future Prophecies   
44917  TRURCEI12903CA4395  Bring the Noise  Future Prophecies   
46566  TRHRNEE12903CFDBD4        Lunar Sea              Camel   

                                     spotify_preview_url  
6013   https://p.scdn.co/mp3-preview/807828ea7070bda7...  
15899  https://p.scdn.co/mp3-preview/d039120c4f5f1e8d...  
29724  https://p.scdn.co/mp3-preview/4d6dbacc93e3ef7e...  
44767  https://p.scdn.co/mp3-preview/13ca5435549b0e46...  
44917  https://p.scdn.co/mp3-preview/d558b155fb9dcfe4...  
46566  https://p.scdn.co/mp3-preview/8bf35f13a0ece173...

In [65]:
a= df_songs[df_songs['track_id'] == 'TROINZB128F932F740']
print(a)
a['track_id'].values.item()


                track_id           name   artist  \
6013  TROINZB128F932F740  Crazy in Love  Beyoncé   

                                    spotify_preview_url  
6013  https://p.scdn.co/mp3-preview/807828ea7070bda7...  


'TROINZB128F932F740'

In [66]:
filtered_songs[filtered_songs['track_id'].isin(recommendations)]

track_id             name             artist  \
3337   TROINZB128F932F740    Crazy in Love            Beyoncé   
8871   TRCVMAF12903D00E61         Delirium          Satyricon   
17287  TRGEUXY128F4226B26  Monday Massacre           Mr. Oizo   
26611  TRYLWIW12903CA438D        Dreadlock  Future Prophecies   
26701  TRURCEI12903CA4395  Bring the Noise  Future Prophecies   
27774  TRHRNEE12903CFDBD4        Lunar Sea              Camel   

                                     spotify_preview_url  
3337   https://p.scdn.co/mp3-preview/807828ea7070bda7...  
8871   https://p.scdn.co/mp3-preview/d039120c4f5f1e8d...  
17287  https://p.scdn.co/mp3-preview/4d6dbacc93e3ef7e...  
26611  https://p.scdn.co/mp3-preview/13ca5435549b0e46...  
26701  https://p.scdn.co/mp3-preview/d558b155fb9dcfe4...  
27774  https://p.scdn.co/mp3-preview/8bf35f13a0ece173...

In [67]:
def collaborative_recommendation(song_name, dask_data, filtered_data, interaction_matrix, k=5 ):
    song_row = filtered_data[filtered_data['name'] == song_name]
    print(song_row)

    #track_id of song name
    input_track_id = song_row['track_id'].values.item()
    print(input_track_id)
    #index value of track id
    ind= np.where(dask_data['track_id'].cat.categories == input_track_id)[0].item()
    print(ind)
    # fetch the input vector
    input_array = interaction_matrix[ind]
    # get similarity scores
    similarity_scores = cosine_similarity(input_array, interaction_matrix)
    similarity_scores = similarity_scores.ravel()
    
    #get top k recommendations
    recommendations_track_ids = dask_data['track_id'].cat.categories[np.argsort(similarity_scores)[-k-1:][::-1]]
    print(recommendations_track_ids)
    top_scores = np.sort(similarity_scores)[-k-1:][::-1] #getting score parameter to sort data based on most similar score while merging df 
    temp_df = pd.DataFrame({"track_id":recommendations_track_ids.tolist(),
                            "score":top_scores})
    print(temp_df)
    top_k_songs = (
        filtered_data.loc[filtered_data['track_id'].isin(recommendations_track_ids)]
        .merge(temp_df, on = "track_id")
        .sort_values( by = 'score', ascending = False)
        .drop(columns = ['track_id', 'score'])
        .reset_index(drop = True)
        

    )
    return top_k_songs




In [68]:
collaborative_recommendation(song_name="Crazy in Love",
                             dask_data=df,
                             filtered_data=filtered_songs,
                             interaction_matrix=sparse_matrix)

                track_id           name   artist  \
3337  TROINZB128F932F740  Crazy in Love  Beyoncé   

                                    spotify_preview_url  
3337  https://p.scdn.co/mp3-preview/807828ea7070bda7...  
TROINZB128F932F740
17018
Index(['TROINZB128F932F740', 'TRURCEI12903CA4395', 'TRYLWIW12903CA438D',
       'TRCVMAF12903D00E61', 'TRHRNEE12903CFDBD4', 'TRGEUXY128F4226B26'],
      dtype='object', name='track_id')
             track_id     score
0  TROINZB128F932F740  1.000000
1  TRURCEI12903CA4395  0.082255
2  TRYLWIW12903CA438D  0.072171
3  TRCVMAF12903D00E61  0.055920
4  TRHRNEE12903CFDBD4  0.055293
5  TRGEUXY128F4226B26  0.054046


name             artist  \
0    Crazy in Love            Beyoncé   
1  Bring the Noise  Future Prophecies   
2        Dreadlock  Future Prophecies   
3         Delirium          Satyricon   
4        Lunar Sea              Camel   
5  Monday Massacre           Mr. Oizo   

                                 spotify_preview_url  
0  https://p.scdn.co/mp3-preview/807828ea7070bda7...  
1  https://p.scdn.co/mp3-preview/d558b155fb9dcfe4...  
2  https://p.scdn.co/mp3-preview/13ca5435549b0e46...  
3  https://p.scdn.co/mp3-preview/d039120c4f5f1e8d...  
4  https://p.scdn.co/mp3-preview/8bf35f13a0ece173...  
5  https://p.scdn.co/mp3-preview/4d6dbacc93e3ef7e...

In [41]:
df = pd.DataFrame({'track_id': ['a', 'b', 'a', 'c']})
df['track_id'] = df['track_id'].astype('category')

track_ids = df['track_id'].cat.categories.values
print(track_ids)

['a' 'b' 'c']


In [42]:
track_idx = df['track_id'].cat.codes
print(track_idx)

0    0
1    1
2    0
3    2
dtype: int8


In [46]:
a = np.where(df['track_id'].cat.categories.values)
a

(array([0, 1, 2], dtype=int64),)

In [39]:
song_row = filtered_songs[filtered_songs['name']== 'Dreadlock']
print(song_row)

                 track_id       name             artist  \
26611  TRYLWIW12903CA438D  Dreadlock  Future Prophecies   

                                     spotify_preview_url  
26611  https://p.scdn.co/mp3-preview/13ca5435549b0e46...  


In [40]:
song_track = song_row['track_id'].values.item()
print(song_track)

TRYLWIW12903CA438D


In [65]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Save to a file
x= np.save('my_array', arr)
x